{{- if not .Values.minio.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glitch-hunt.fullname" . }}-minio
  labels:
    {{- include "glitch-hunt.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ required "minio.accessKey is required when existingSecret is not set" .Values.minio.accessKey | b64enc | quote }}
  secret-key: {{ required "minio.secretKey is required when existingSecret is not set" .Values.minio.secretKey | b64enc | quote }}
{{- end }}
