{{- if not .Values.minio.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glitch-hunt.fullname" . }}-minio
  labels:
    {{- include "glitch-hunt.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ default "admin-de1b7035" .Values.minio.accessKey | b64enc | quote }}
  secret-key: {{ default "4MoXVEV2WHEpb90hfWpmGIdafqFH95pC" .Values.minio.secretKey | b64enc | quote }}
{{- end }}
