apiVersion: v1
kind: Service
metadata:
  name: {{ include "glitch-hunt.fullname" . }}-redis
  labels:
    {{- include "glitch-hunt.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "glitch-hunt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
