apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glitch-hunt.fullname" . }}-minio
  labels:
    {{- include "glitch-hunt.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.minio.accessKey | b64enc | quote }}
  secret-key: {{ .Values.minio.secretKey | b64enc | quote }}
